// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PillDispenserWeb.Models;
using System;

namespace PillDispenserWeb.Migrations.AppData
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20171118005100_DoctorPatientInitialCreate")]
    partial class DoctorPatientInitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PillDispenserWeb.Models.DataTypes.Doctor", b =>
                {
                    b.Property<long>("DoctorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<long?>("PatientId");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("PillDispenserWeb.Models.DataTypes.Medication", b =>
                {
                    b.Property<string>("MedicationId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("DosageInMg");

                    b.Property<string>("PlaintextName");

                    b.HasKey("MedicationId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("PillDispenserWeb.Models.DataTypes.Patient", b =>
                {
                    b.Property<long>("PatientId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("DoctorId");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("PatientId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PillDispenserWeb.Models.DataTypes.Doctor", b =>
                {
                    b.HasOne("PillDispenserWeb.Models.DataTypes.Patient")
                        .WithMany("Doctors")
                        .HasForeignKey("PatientId");
                });

            modelBuilder.Entity("PillDispenserWeb.Models.DataTypes.Patient", b =>
                {
                    b.HasOne("PillDispenserWeb.Models.DataTypes.Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId");
                });
#pragma warning restore 612, 618
        }
    }
}
